language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

## Cache composer
cache:
  directories:
  - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
- vendor/bin/phpcs --standard=PSR2 src/
- vendor/bin/phpunit --coverage-text  --coverage-clover=coverage.clover
