language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

## Cache composer
cache:
  directories:
  - $HOME/.composer/cache

install:
  - composer install --dev --no-interaction
  - composer require --dev php-coveralls/php-coveralls

script:
  - vendor/bin/phpcs --standard=PSR2 src/
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
